GLA-731: Upgrade Luniverse-Gluwacoin to solidity 0.8
gluwa/Luniverse-Gluwacoin pull request #20
Opened 2022-03-21 21:08 UTC by marc-aurele-besner

## Notable changes:
- Upgrade contracts to Solidity 0.8.12
- 100% coverage test
- Deployment scripts to deploy one or all contracts;
- CLI UI to easily run all deployment, test, and more;
- Log of all deployed contracts per network;
- Move most of the config in hardhat.config.js file
- Move RPC and private key in .env.development
- Tool in cli to setup environment variables (private key and rpc)

## CLI UI usage
`npm run cli`

### Main options
- Setup all environment variables (rpc + private key)
- Run tests (select a test and a network, if not hardhat, it will use contract address from contractsAddressDeployed.json (if existent))
- Deploy contracts (select a contracts or all and a network)
- Deploy all contracts and run the tests sele (select a test and a network)
- Get account balance (Select a network)
- Get the previously deployed contract's address (if contractsAddressDeployed.json exist)
- Get all the previously deployed contracts address (if contractsAddressDeployedHistory.json exist)
- contractsAddressDeployed.json keep the last contracts of each network that you deployed (no duplicate)
- contractsAddressDeployedHistory.json keep ALL contracts deployed

### Coverage Test Result
![Coverage Test Result](https://i.ibb.co/vLcPwmy/Luniverse0-8-12-Test-Coverage.png)

2022-03-22 21:54 UTC, kevinnguyen17 commented on contracts/abstracts/ERC20Pausable.sol
> +contract ERC20Pausable is BeforeTransferERC20, PausableUpgradeable {
We do not need this contract anymore, just use the PausableUpgradeable

2022-03-22 22:02 UTC, kevinnguyen17 requested changes

2022-03-22 22:02 UTC, kevinnguyen17 commented on contracts/abstracts/Reservable.sol
> +        unchecked {
This one can't use unchecked, we must remove the unchecked so solidity will revert if there is overlow

2022-03-23 19:32 UTC, kevinnguyen17 reviewed
should add in pragma ^ so that all the minor versions of 0.8.0 will be supported.

2022-03-23 21:55 UTC, kevinnguyen17 requested changes

2022-03-23 21:55 UTC, kevinnguyen17 commented on contracts/abstracts/ETHlessTransfer.sol
> +        _useNonce(sender, 3, nonce); // 3 - Transfer
Must use sigDomain.Transfer

2022-03-23 21:55 UTC, kevinnguyen17 commented on contracts/LuniverseGluwacoin.sol
> +        _useNonce(burner, 1, nonce); // 1 - Burn
must use SigDomain

2022-03-23 21:55 UTC, kevinnguyen17 commented on contracts/LuniverseGluwacoin.sol
> +        _useNonce(sender, 4, nonce); // 4 - Reserve
must use SigDomain

2022-03-23 21:55 UTC, kevinnguyen17 commented on contracts/abstracts/BeforeTransferERC20.sol
> +    function _useNonce(address signer, uint8 domain, uint256 nonce) internal {
can change the uint8 domain to SigDomain to enhance readability

2022-03-23 23:35 UTC, kevinnguyen17 approved these changes

2022-03-24 00:45 UTC, ohyung1287 approved these changes

2022-03-24 12:50 UTC, merged